---
- hosts: localhost
  connection: local
  vars:
    f5_syslog_parser: "parsers/f5_syslog_parser.yml"
    f5_snmp_basics_parser: "parsers/f5_snmp_basics_parser.yml"
    f5_snmp_trap_parser: "parsers/f5_snmp_trap_parser.yml"
    f5_snmp_communities_parser: "parsers/f5_snmp_communities_parser.yml"
  tasks:
    - name: parse a f5 single line command output
      command: grep "syslog" myfile.txt
      register: syslog_output

    - name: set the syslog host fact
      set_fact:
        syslog_host: "{{ syslog_output.stdout | parse_cli(f5_syslog_parser) }}"

    - name: >
        parse snmp output from a single line f5 command output
      command: grep "sys snmp" f5_config_one_line.txt
      register: snmp_output

    - name: >
        create snmp fact part 1: basic info - sys location
      set_fact:
          snmp:
            basic: "{{ (snmp_output.stdout | parse_cli(f5_snmp_basics_parser))['basic'] }}"
            traps: "{{ (snmp_output.stdout | parse_cli(f5_snmp_trap_parser))['traps'] }}"
            communities: "{{ (snmp_output.stdout | parse_cli(f5_snmp_communities_parser))['communities'] }}"
